runtime: python27
api_version: 1
threadsafe: no
# App Engine default is 10m.
default_expiration: "12h"

handlers:
# Storage API.
- url: /storage
  script: storage.py
  secure: always

# Error reporting.
- url: /errorReporter
  script: errorReporter.py
  secure: always

# Index page.
- url: /
  static_files: index.html
  upload: index\.html
  secure: always
- url: /index/
  static_dir: index
  secure: always


# Source files and uncompiled versions.
skip_files:
# App Engine default patterns.
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
# Custom skip patterns.
- ^third-party/ace/snippets/.*$
- ^third-party/blockly/\.github/.*$
- ^third-party/blockly/externs/.*$
- ^third-party/blockly/msg/json/.*$
- ^third-party/JS-Interpreter/demos.*$
- ^third-party/JS-Interpreter/[^c].*$  # Only serve compressed.js.
- ^.+\.md$
